CREATE DATABASE IF NOT EXISTS Mymvc DEFAULT CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI;

USE Mymvc;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT(20) UNSIGNED  AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(32) NOT NULL,
    PRIMARY KEY(id)
);